name = 'rq-arbiter'
version = '0.0.1'
description = 'An arbiter for Redis Queue'
author = 'Stephane Wirtel'
author_email = 'stephane@wirtel.be'
license = 'MIT'
url = 'https://github.com/matrixise/rq-arbiter'
